### ISSUE TITLE
How do I set the overlay-image?

### ISSUE THREAD

**Issue by zergiocosta** [wkevina/okstate-plugin-camera-overlay#2]
I'm trying to implement an overlay-functionality to my app and found your plugin. But I can't find out how do I set the image that should overlay the camera image. =/

I mean... the camera is working fine. I just can't find out how to overlay that image with another one through js or obj-c coding...

**Comment by evandentremont** [comment]
bump

**Comment by ghost** [comment]
It appears to be passed to options https://github.com/wkevina/okstate-plugin-camera-overlay/blob/b4d5df11ac5530d22e14fdb844ef45c85402d355/www/Camera.js#L62

**Comment by danocaFR** [comment]
What do you need to write ?

This : 
navigator.camera.getPicture(onCapturePhoto, onFail, {
        quality: 100,
        overlayImageURL: 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
    });

Or this :
navigator.camera.getPicture(onCapturePhoto, onFail, {
        quality: 100,
        overlayImageURL: 'www/images/mask.png'
    });

This plugin works with Android 5/6 and iOS 9/10 ?

Thank you
